# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileOutputModifier-Copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    An object class representing the main graphical window for a 'Ui_MainWindow' object.
    """
    def setupUi(self, MainWindow) -> None:
        """
        Function to set up the positions and attributes of objects to display within the user interface.
        :param MainWindow: The graphical window type the Ui_MainWindow object will display as a QtWidgets.QMainWindow() function.
        :return: None
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 800)
        MainWindow.setMinimumSize(QtCore.QSize(540, 800))
        MainWindow.setMaximumSize(QtCore.QSize(540, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(190, 0, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.textBrowser_outputpreview = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_outputpreview.setGeometry(QtCore.QRect(150, 460, 271, 191))
        self.textBrowser_outputpreview.setObjectName("textBrowser_outputpreview")
        self.label_outputpreview = QtWidgets.QLabel(self.centralwidget)
        self.label_outputpreview.setGeometry(QtCore.QRect(190, 430, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_outputpreview.setFont(font)
        self.label_outputpreview.setObjectName("label_outputpreview")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(220, 40, 121, 21))
        self.label_input.setObjectName("label_input")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(220, 70, 121, 22))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.label_filenotfound = QtWidgets.QLabel(self.centralwidget)
        self.label_filenotfound.setGeometry(QtCore.QRect(210, 100, 161, 20))
        self.label_filenotfound.setObjectName("label_filenotfound")
        self.pushButton_setoutput = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setoutput.setGeometry(QtCore.QRect(220, 690, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_setoutput.setFont(font)
        self.pushButton_setoutput.setObjectName("pushButton_setoutput")
        self.label_outputcheck = QtWidgets.QLabel(self.centralwidget)
        self.label_outputcheck.setGeometry(QtCore.QRect(180, 660, 231, 16))
        self.label_outputcheck.setObjectName("label_outputcheck")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(220, 130, 121, 21))
        self.label_output.setObjectName("label_output")
        self.lineEdit_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output.setGeometry(QtCore.QRect(220, 160, 121, 22))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.label_outputfile = QtWidgets.QLabel(self.centralwidget)
        self.label_outputfile.setGeometry(QtCore.QRect(160, 190, 241, 20))
        self.label_outputfile.setObjectName("label_outputfile")
        self.label_outputoptions = QtWidgets.QLabel(self.centralwidget)
        self.label_outputoptions.setGeometry(QtCore.QRect(210, 230, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_outputoptions.setFont(font)
        self.label_outputoptions.setObjectName("label_outputoptions")
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_1.setGeometry(QtCore.QRect(190, 260, 151, 20))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(190, 320, 181, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 290, 251, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_replacing = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_replacing.setGeometry(QtCore.QRect(140, 390, 113, 22))
        self.lineEdit_replacing.setObjectName("lineEdit_replacing")
        self.lineEdit_replacer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_replacer.setGeometry(QtCore.QRect(300, 390, 113, 22))
        self.lineEdit_replacer.setObjectName("lineEdit_replacer")
        self.label_replacing = QtWidgets.QLabel(self.centralwidget)
        self.label_replacing.setGeometry(QtCore.QRect(130, 360, 131, 16))
        self.label_replacing.setObjectName("label_replacing")
        self.label_replacement = QtWidgets.QLabel(self.centralwidget)
        self.label_replacement.setGeometry(QtCore.QRect(290, 360, 151, 16))
        self.label_replacement.setObjectName("label_replacement")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow) -> None:
        """
        Function to set and specify the text the different objects will display on the graphical user interface.
        :param MainWindow: The graphical window type the Ui_MainWindow object will display as a QtWidgets.QMainWindow() function.
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Output Modifier"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">File Output Modifier</p></body></html>"))
        self.textBrowser_outputpreview.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_outputpreview.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Send To Output Preview</p></body></html>"))
        self.label_input.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Input File As A .txt</p></body></html>"))
        self.label_filenotfound.setText(_translate("MainWindow", "This File Cannot Be Found"))
        self.pushButton_setoutput.setText(_translate("MainWindow", "Set To Output"))
        self.label_outputcheck.setText(_translate("MainWindow", "Cannot Output With No Output Specified"))
        self.label_output.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Output File As A .txt</p></body></html>"))
        self.label_outputfile.setText(_translate("MainWindow", "This Will Override An Existing Output File\n"
"This Will Create A New Output File"))
        self.label_outputoptions.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Output Options</p></body></html>"))
        self.radioButton_1.setText(_translate("MainWindow", "Output The File As Is"))
        self.radioButton_3.setText(_translate("MainWindow", "Output The File In Reverse"))
        self.radioButton_2.setText(_translate("MainWindow", "Output The File With Strings Replaced"))
        self.label_replacing.setText(_translate("MainWindow", "String To Be Replaced"))
        self.label_replacement.setText(_translate("MainWindow", "String To Be Replacement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
